name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install -y sbcl libgirepository1.0-dev libgtk-3-dev xvfb
    - name: Install Quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp &&
        sbcl \
          --load quicklisp.lisp \
          --eval '(quicklisp-quickstart:install)' \
          --quit
        echo '(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                                     (user-homedir-pathname))))
                      (when (probe-file quicklisp-init)
                        (load quicklisp-init)))' > $HOME/.sbclrc
    - name: Add system to Quicklisp catalog
      run: |
        ln -s $(pwd) ~/quicklisp/local-projects/cl-gobject-introspection &&
        rm -f ~/quicklisp/local-projects/system-index.txt

    - name: Run tests
      run: |
        sbcl \
          --eval '(ql:quickload :fiveam)' \
          --eval '(ql:quickload :cl-gobject-introspection)' \
          --eval '(setf fiveam:*debug-on-error* t fiveam:*debug-on-failure* t)' \
          --eval '(setf *debugger-hook* (lambda (c h) (declare (ignore h)) (princ c) (uiop:quit -1)))' \
          --eval '(asdf:test-system :cl-gobject-introspection)' \
          --quit
